In [2]:
import numpy as np
import pandas as pd

HW Questions (Numpy):

In [15]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
a = np.array([[1,2,3,4]])
b = np.array([[4,5,6,7]])
ab_v = np.vstack((a,b))
ab_h = np.hstack((a,b))
print(ab_v, ab_h)

[[1 2 3 4]
 [4 5 6 7]] [[1 2 3 4 4 5 6 7]]


In [16]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
aUb = np.intersect1d(a,b)
print(aUb)

[4]


In [27]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
np.where((a[:,] > 2) & (a[:,] < 5))

(array([0, 0], dtype=int64), array([2, 3], dtype=int64))

In [ ]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))


(array([ 11,  24,  29,  30,  57, 106], dtype=int64),)

HW Questions (Pandas):

In [ ]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df_filter = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
df_filter.head()

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [38]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'].fillna(df['Max.Price'].mean())
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9       18.8      25.0   
1          NaN   Legend  Midsize  29.200000   33.9       38.7      18.0   
2         Audi       90  Compact  25.900000   29.1       32.3      20.0   
3         Audi      100  Midsize  17.118605   37.7       44.6      19.0   
4          BMW     535i  Midsize  17.118605   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [50]:
# 3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   38  22  37  38
1   18  38  32  24
2   28  21  32  28
3   22  12  39  23
4   29  17  25  20
5   21  38  18  11
6   29  25  13  39
7   32  20  29  16
8   11  14  10  36
9   24  37  13  36
10  39  19  33  21
11  25  36  20  28
12  23  32  37  32
13  15  16  13  32
14  34  27  22  16

In [51]:
print(df[df.sum(axis=1) > 100])

     0   1   2   3
0   38  22  37  38
1   18  38  32  24
2   28  21  32  28
6   29  25  13  39
9   24  37  13  36
10  39  19  33  21
11  25  36  20  28
12  23  32  37  32
